import { Onest } from "next/font/google";
import "./globals.css";


const onest = Onest({
  variable:"--font-onest",
  subsets: ['latin'],
 
});

export const metadata = {
  title: "Esha Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${onest.variable}`}>
        {children}
      </body>
    </html>
  );
}
